# Find version components
STRING (REGEX REPLACE "^([0-9]+).*" "\\1" CSIM_MAJOR_VERSION "${CSIM_VERSION}")
STRING (REGEX REPLACE "^[0-9]+\\.([0-9]+).*" "\\1" CSIM_MINOR_VERSION "${CSIM_VERSION}")
STRING (REGEX REPLACE "^[0-9]+\\.[0-9]+\\.([0-9]+)" "\\1" CSIM_REVISION_VERSION ${CSIM_VERSION})
STRING (REGEX REPLACE "^[0-9]+\\.[0-9]+\\.[0-9]+(.*)" "\\1" CSIM_CANDIDATE_VERSION ${CSIM_VERSION})
